### ISSUE TITLE
Does postcss-media-variables work with precss?

### ISSUE THREAD

**Issue by rfender** [WolfgangKluge/postcss-media-variables#6]
I am running a series of PostCSS plugins in the order shown below. When using the **postcss-media-variables**, all media queries are removed from the output.

**package.json script**
`postcss --use precss --use postcss-media-variables --use autoprefixer --use postcss-calc --use postcss-media-variables`

**css files**
`.my-class {
    padding-top: 0;
    border-bottom: none;

```
@media (max-width: calc($(screen-sm-min) - 1)) {
    padding-left: 0;
    padding-right: 0;
}
```

}`

**Comment by WolfgangKluge** [comment]
Hi @rfender,
sorry, I'm not (yet) able to reproduce the problem.

```css
$screen-sm-min: 200px;

.my-class {
  padding-top: 0;
  padding-bottom: 0;
  @media (max-width: calc($(screen-sm-min) - 1)) {
    padding-left: 0;
    padding-right: 0;
  }
}
```

After running the command above, I get
```css
.my-class {
  padding-top: 0;
  padding-bottom: 0
}
  @media (max-width: 199px) {
  .my-class {
    padding-left: 0;
    padding-right: 0
  }
}
```
That seems ok to me. `postcss-media-variables` is not involved, though (since there is no (css-)variable in the @media line - the replacement of `$(..) is done through precss...)


If I have no matching variable, the output is
```css
.my-class {
  padding-top: 0;
  padding-bottom: 0
}
  @media (max-width: calc($(screen-sm-min) - 1)) {
  .my-class {
    padding-left: 0;
    padding-right: 0
  }
}
```
and that's seems to be OK, too (`post-css-media-variables` needs a variable to be accessed like `var(--varname)`)

---

I encountered some problems with postcss v2 - sorry. Until now I had no time to investigate it further.. Fixes are very welcome ;)
