### ISSUE TITLE
Is this package compatible with postcss-loader?

### ISSUE THREAD

**Issue by SammyM** [WolfgangKluge/postcss-media-variables#8]
I cannot seem to get this plugin to work.

I'm using `postcss-loader` through webpack 2 and I have the following in my PostCSS config file:
```
module.exports = () => ({
  plugins: {
    'postcss-import': {},
    'postcss-media-variables': {},
    'postcss-cssnext': {
      browsers: ['last 2 versions']
    }
  }
});
```

Here are the version numbers of the packages I'm using:
```
"postcss-cssnext": "^2.10.0",
"postcss-import": "^9.1.0",
"postcss-loader": "^1.3.3"
```

The output of this results in the following:
```
::-postcss-media-variables {-postcss-media-run: 1 }
::-postcss-media-variables {-pcs-mv-40-12e: 500px }

@media (max-width:-pcs-mv-40-12e) {
  ::-postcss-media-variables {
    .zOWzDY-App-h1-heading {
      background: red;
    }
  }
}
```

I tried adding in the `postcss-media-variables` plugin twice in my PostCSS config file, but this didn't seem to make a difference.

Do you know of a way to get this working with `postcss-loader`?

**Comment by WolfgangKluge** [comment]
Could you show me the input file?

**Comment by SammyM** [comment]
Do you mean the CSS? This is what I was testing it out with:

```
:root {
  --breakpoint: 500px;
}

@media (max-width: var(--breakpoint)) {
  .h1-heading {
    background: red;
  }
}
```

(I'm using CSS modules, I don't know if that's relevant).

**Comment by WolfgangKluge** [comment]
I cannot really reproduce your issue, but I think the main problem is in the configuration.

> `postcss-media-variables` has to be used **twice!**

You can see it in the example I've provided
```js
var output = postcss([
        mediaVariables(), // first run
        customMedia(/* options */),
        cssVariables(/* options */),
        calc(/* options */),
        mediaVariables() // second run
    ])
    .process(mycss)
    .css;
```

The problem now is, that you are using a json-like configuration
```js
module.exports = () => ({
  plugins: {
    'postcss-import': {},
    'postcss-media-variables': {},
    'postcss-cssnext': {
      browsers: ['last 2 versions']
    }
  }
});
```
And there you cannot simply add another key with the name `postcss-media-variables`.
So I would give the syntax here https://github.com/postcss/postcss-loader#plugins a try (it seems like plugins could be a method, too) - so in your case it would be something like

```js
module.exports = () => ({
  plugins: () => [
    require('postcss-import')(),
    require('postcss-media-variables')(),
    require('postcss-cssnext')({
      browsers: ['last 2 versions']
    }),
    require('postcss-media-variables')()
  ]
});
```

I've not tested it.. (Please provide a complete example to investigate further...)

**Comment by CyberAP** [comment]
Having the same issue. Done the config above and getting something weird this instead of actual values:
```css
@custom-media --mq-page-width-max (max-width:-pcs-mv-1-39e);
@custom-media --mq-page-width-min (min-width:-pcs-mv-2-39e);
```
```css
@media (--mq-page-width-min) {
    .mq-not-page-width {
        display: none
    }
}
```

Variables are set in `:root`:

```css
:root
{
  --screen-mobile: 600px;
  --screen-desktop: 1024px;
}
```

Then used like this:
```css
@custom-media --mq-page-width-max        (max-width: var(--page-width));
@custom-media --mq-page-width-min        (min-width: var(--page-width));

@media (--mq-page-width-max)
{
  .mq-page-width-only
  {
    display: none;
  }
}
```

My postcss config:

```javascript
module.exports = {
  plugins: [
    require('postcss-media-variables')(),
    require('postcss-normalize')(),
    require('postcss-preset-env')(),
    require('postcss-media-variables')(),
    require('autoprefixer'),
  ]
};
```

**Comment by CyberAP** [comment]
Figured out you have to adjust which features are being polyfilled first. Custom media is a Stage 1, so you have to set that explicitly in preset env config, like this:

```js
module.exports = {
  plugins: [
    require('postcss-media-variables')(),
    require('postcss-normalize')(),
    require('postcss-preset-env')({
      stage: 1,
    }),
    require('postcss-media-variables')(),
    require('autoprefixer')(),
  ]
};
```

But even after that I am not getting the desired result. My media queries still look like this:

```css
@media (max-width: var(--page-width)) {
    .mq-page-width-only {
        display:none
    }
}
```

**Comment by AlexWayfer** [comment]
I have the same problem. I don't want to write common JavaScript code with file system interactions, I just want to use JSON-like config. It's weird and sadly that this very useful plugin requires to be ran twice.

**Comment by quiin** [comment]
Has anyone been able to use this alongside `postcss-loader`? 
Like O.P, the outputs I get are not what I'm expecting:

Config:
```js
config.module.rules.push({
  test: /\.s?css$/,
  use: [
    'style-loader',
    { loader: 'css-loader', options: { modules: true, importLoaders: 1 } },
    {
      loader: 'postcss-loader',
      options: {
        postcssOptions: {
          ident: 'postcss',
          plugins: [
            mediaVariables(),
            mediaVariables(),
          ]
        }
      }
    },
    'sass-loader',
  ],
  include: path.resolve(__dirname, '../'),
});
```


Input:
```scss
:root {
  --breakpoint-sm: 200px;
}

@media (min-width: var(--breakpoint-sm)) {
  .content {
    color: red;
  }
}
```

Output (exactly the same):
```scss
@media (min-width: var(--breakpoint-sm)) {
  .content {
    color: red;
  }
}
```
